<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LG4283L" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="2020-06-13T10:28:44 IST" time="0.039" errors="0">
  <testcase name="Demo2" time="0.007" classname="Test.Day2"/>
  <testcase name="Demo" time="0.008" classname="Test.Basic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Basic.Demo(Basic.java:20)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="MobileLoginHommeLoan" time="0.008" classname="Test.Day4"/>
  <testcase name="WebLoginHomeLoan" time="0.001" classname="Test.Day4"/>
  <testcase name="APILoginHomeLoan" time="0.001" classname="Test.Day4"/>
  <testcase name="Demo1" time="0.0" classname="Test.Basic">
    <ignored/>
  </testcase> <!-- Demo1 -->
</testsuite> <!-- Personal Loan -->
